### ISSUE TITLE
Dataset Link Not Found

### ISSUE THREAD

**Issue by HildaNya** [bytedance/neurst#52]
I'm trying to recreate results for research purposes. However, it seems that the dataset used in the end-to-end model (found here https://persyval-platform.univ-grenoble-alpes.fr/DS91/detaildataset) is not available anymore. Is there another place I could find this data? Thanks!

**Comment by zhaocq-nlp** [comment]
You can either use MuST-C dataset instead or concat me at zhaocq.nlp@gmail.com. I have backups for this dataset.
