### ISSUE TITLE
Speech Transformer Issue

### ISSUE THREAD

**Issue by HildaNya** [bytedance/neurst#54]
Hi. I'm trying to reproduce the speech transformer portion but have encountered an issue while training.
My setup used the example given:
```
python3 -m neurst.cli.run_exp \
    --config_paths /path_to_data/asr_st/asr_training_args.yml,/path_to_data/asr_st/asr_validation_args.yml \
    --hparams_set speech_transformer_s \
    --model_dir /path_to_data/asr_st/asr_benchmark
```
The system is producing this
```
TypeError: graph() got an unexpected keyword argument 'step'
```

I'm trying to isolate the issue and see if it's a dependency issue. Any help is appreciated.

**Comment by zhaocq-nlp** [comment]
Hi, could you please check the version of TensorFlow? TensorFlow 2.4.1 should be stable.

**Comment by HildaNya** [comment]
Ahh. Thanks so much.
