### ISSUE TITLE
speech_transformer ST验证阶段问题

### ISSUE THREAD

**Issue by jannicaTan** [bytedance/neurst#58]
您好，我在复现augmented_librispeech的时候出现了以下问题：
1.验证ASR效果时，我的WER为100+，离result的8差的有点远😂
因为设备的原因，我把`train_steps`修改为10000（原来的1/20），`batch_size`降低为60000（原来的1/2）
请问是不是提高train_steps就可以有效改变？（正打算重新修改参数再跑一次），还是其他的原因呢？

2.在ST训练阶段的验证，我发现不管听到的是什么，每一次的hypothesis都显示为同一句话（如图），请问是什么原因呢？
<img width="1208" alt="ST重复翻译" src="https://user-images.githubusercontent.com/86825008/171625865-70e68e0c-172c-4921-9977-1ecd26e40b01.png">

**Comment by zhaocq-nlp** [comment]
你好可以确认一下两个问题
1. GPU型号是否支持混合精度训练，如果不支持，在训练的时候加上`--dtype float32`来换回全精度训练
2. 还没收敛应该就是训练步数过少的原因，至少到20000 step之后再看下效果

**Comment by jannicaTan** [comment]
> 你好可以确认一下两个问题
> 
> 1. GPU型号是否支持混合精度训练，如果不支持，在训练的时候加上`--dtype float32`来换回全精度训练
> 2. 还没收敛应该就是训练步数过少的原因，至少到20000 step之后再看下效果

非常感谢！我用了2张2080 Ti  它是支持混合精度训练的，之前的问题就是步数太少的原因，增加后有效果，WER在30000step后测试集验证可以达到12.67！😄

还想问一下关于bleu的计算问题，我通过预训练ASR去训练ST，50000step后出来的bleu评分如下，请问readme给出的结果中18.3是如何计算的？感觉不是单纯的✖️100
<img width="1158" alt="uTools_1654337854588" src="https://user-images.githubusercontent.com/86825008/172000596-40187865-8df2-41f7-9bbd-3396c6ac000e.png">
我查了相关文件，我理解的测试集验证过程是：运行`run_exp.py`->根据配置文件中的entry类型判断为`pridict`->执行`exps/evaluate.py`->根据配置文件中的metric类型文件为‘bleu'->执行`metrics/bleu.py`文件。请问这个过程是理解正确嘛？
但是为什么`tok_bleu`的return bleu✖️100(第420行)，但是其他的不需要✖️100？🤔️

**Comment by zhaocq-nlp** [comment]
log里的BLEU不需要再乘100，这个结果意味着没收敛，可以检查下看看encoder初始化是否成功。 训练日志前面检索下`pretrain_model`相关的，看下是否成功初始化了所有encoder参数

**Comment by jannicaTan** [comment]
> log里的BLEU不需要再乘100，这个结果意味着没收敛，可以检查下看看encoder初始化是否成功。 训练日志前面检索下`pretrain_model`相关的，看下是否成功初始化了所有encoder参数

谢谢您的提醒！最终原因其实是我读取的预训练模型路径写错了，多写了一个/，导致没有读取到。
目前已经复现出ST+ASR pretrain的结果了！😄

请问如果我想把数据集切换成除了提供的可进行处理的8种语言外的源语言，有什么推荐的方法或者规定的格式吗？

**Comment by zhaocq-nlp** [comment]
可以参考下数据预处理以及打包成TF-Record的过程。只要TF-Record的格式跟现在使用的一致就行。

**Comment by jannicaTan** [comment]
好的我尝试一下～谢谢解答！
