### ISSUE TITLE
How to continue training from a saved checkpoint

### ISSUE THREAD

**Issue by HildaNya** [bytedance/neurst#59]
Hi. I have limited walltime for GPU usage so I can only train a certain amount of steps each time. I'd like to continue training from the last saved checkpoint, so I can get a greater number of training steps. Is there a way to configure the training to start from a certain step?

Thanks!

**Comment by zhaocq-nlp** [comment]
Just use the save `model_dir:` in your configuration file or the save `--model_dir` option.

**Comment by HildaNya** [comment]
Thank you.
