### ISSUE TITLE
How to achieve Transformer ST + ASR pretrain

### ISSUE THREAD

**Issue by HildaNya** [bytedance/neurst#61]
Hi. I'm currently trying to reproduce and extend the Transformer ST + ASR model. But I'm a bit confused on how to achieve the pertaining. Specifically, should the lines below be added to the configuration for asr?
```
    --pretrain_model /path_to_data/asr_st/asr_benchmark/best_avg \
    --pretrain_variable_pattern "(TransformerEncoder)|(input_audio)"
```
Would it be possible to have an example for ST+ASR? Thanks!

**Comment by zhaocq-nlp** [comment]
Hi. These two options are used for initializing the parameters of ST encoder, i.e., the training process will first read the ASR checkpoint from `pretrain_model` and find the varibale names matched the regex pattern `pretrain_variable_pattern` and overwrite the initial values of those in ST. You can read the training log to see all variable names. Here the `"(TransformerEncoder)|(input_audio)"` means the encoder and audio representation layers. 

And I wonder what is the ST+ASR? Does it mean jointly training ST and ASR?

**Comment by HildaNya** [comment]
Thanks for the explanation. Sorry about my confusing wording. By ST + ASR I meant the model "Transformer ST + ASR pretrain", which on the must-c page, it was stated that this model had a 21.9 BLEU score. 
![neurst](https://user-images.githubusercontent.com/89824394/172530853-8cec3ab3-e206-44a0-98bd-20913d47afa3.png)
I'm a bit unsure what commands I need to recreate that model.
Thanks!

**Comment by zhaocq-nlp** [comment]
```
    --pretrain_model /path_to_data/asr_st/asr_benchmark/best_avg \
    --pretrain_variable_pattern "(TransformerEncoder)|(input_audio)"
```
Add these two options during ST training means "Transformer ST+ASR pretrain"

**Comment by HildaNya** [comment]
Thanks.
